const {
  AndroidConfig,
  withAndroidManifest,
  withInfoPlist,
  withPodfile,
  withSettingsGradle,
} = require('@expo/config-plugins');

const INSTALL_PACKAGES_PERMISSION = 'android.permission.REQUEST_INSTALL_PACKAGES';
const FORBIDDEN_STORE_PERMISSIONS = [
  INSTALL_PACKAGES_PERMISSION,
  'android.permission.SYSTEM_ALERT_WINDOW',
  'android.permission.READ_EXTERNAL_STORAGE',
  'android.permission.WRITE_EXTERNAL_STORAGE',
];
const ANDROID_PERMISSION_ELEMENTS = ['uses-permission', 'uses-permission-sdk-23'];
const UPDATER_PACKAGE = 'folio-updater';
const DEVELOPMENT_CLIENT_PACKAGES = [
  'expo-dev-client',
  'expo-dev-launcher',
  'expo-dev-menu',
  'expo-dev-menu-interface',
];
const STORE_AUTOLINKING_EXCLUSIONS = [UPDATER_PACKAGE, ...DEVELOPMENT_CLIENT_PACKAGES];
const STORE_AUTOLINKING_MARKER = '// @generated by withFolioDistributionGuard: store autolinking';
const STORE_PODFILE_MARKER = '# @generated by withFolioDistributionGuard: store autolinking';

function quotedPackageList() {
  return `[${STORE_AUTOLINKING_EXCLUSIONS.map((packageName) => JSON.stringify(packageName)).join(', ')}]`;
}

function applyStoreAutolinkingGradleGuard(source) {
  if (source.includes(STORE_AUTOLINKING_MARKER)) return source;
  const anchor = 'extensions.configure(com.facebook.react.ReactSettingsExtension)';
  if (!source.includes(anchor)) {
    throw new Error(
      '[withFolioDistributionGuard] Could not locate the Expo autolinking settings anchor.',
    );
  }
  const guard = `${STORE_AUTOLINKING_MARKER}
def folioStoreAutolinkingExclusions = ${quotedPackageList()}
expoAutolinking.exclude = folioStoreAutolinkingExclusions
if (!expoAutolinking.exclude.containsAll(folioStoreAutolinkingExclusions)) {
  throw new GradleException("Store builds must exclude updater and development-client modules from Android autolinking.")
}

`;
  return source.replace(anchor, `${guard}${anchor}`);
}

function assertStoreAutolinkingGradleGuard(source) {
  if (
    !source.includes(STORE_AUTOLINKING_MARKER)
    || !source.includes(`expoAutolinking.exclude = folioStoreAutolinkingExclusions`)
    || !source.includes(`folioStoreAutolinkingExclusions = ${quotedPackageList()}`)
    || !source.includes('containsAll(folioStoreAutolinkingExclusions)')
  ) {
    throw new Error(
      '[withFolioDistributionGuard] Generated settings.gradle does not fail closed with the ' +
      'store-only native-module exclusions. Re-run prebuild with FOLIO_DISTRIBUTION=store.',
    );
  }
}

function applyStorePodfileAutolinkingGuard(source) {
  if (source.includes(STORE_PODFILE_MARKER)) return source;
  const matches = source.match(/^[ \t]*use_expo_modules![ \t]*$/gm) ?? [];
  if (matches.length !== 1) {
    throw new Error(
      '[withFolioDistributionGuard] Could not locate the single SDK 57 use_expo_modules! call.',
    );
  }
  const call = matches[0];
  const indentation = call.match(/^[ \t]*/)?.[0] ?? '';
  return source.replace(
    call,
    `${indentation}${STORE_PODFILE_MARKER}\n` +
      `${indentation}use_expo_modules!(exclude: ${quotedPackageList()})`,
  );
}

function assertStorePodfileAutolinkingGuard(source) {
  if (
    !source.includes(STORE_PODFILE_MARKER)
    || !source.includes(`use_expo_modules!(exclude: ${quotedPackageList()})`)
  ) {
    throw new Error(
      '[withFolioDistributionGuard] Generated Podfile does not fail closed with the ' +
      'store-only native-module exclusions. Re-run prebuild with FOLIO_DISTRIBUTION=store.',
    );
  }
}

function removeDevelopmentClientAndroidSchemes(androidManifest) {
  for (const application of androidManifest.manifest.application ?? []) {
    for (const activity of application.activity ?? []) {
      for (const intentFilter of activity['intent-filter'] ?? []) {
        if (!Array.isArray(intentFilter.data)) continue;
        intentFilter.data = intentFilter.data.filter(
          (entry) => !entry.$?.['android:scheme']?.toLocaleLowerCase().startsWith('exp+'),
        );
      }
    }
  }
  return androidManifest;
}

function assertNoDevelopmentClientAndroidScheme(androidManifest) {
  const serialized = JSON.stringify(androidManifest);
  if (/"android:scheme":"exp\+/i.test(serialized)) {
    throw new Error(
      '[withFolioDistributionGuard] Expo development-client scheme leaked into AndroidManifest.xml.',
    );
  }
}

function removeDevelopmentClientInfoPlist(infoPlist) {
  if (Array.isArray(infoPlist.CFBundleURLTypes)) {
    infoPlist.CFBundleURLTypes = infoPlist.CFBundleURLTypes
      .map((entry) => ({
        ...entry,
        CFBundleURLSchemes: (entry.CFBundleURLSchemes ?? []).filter(
          (scheme) => !scheme.toLocaleLowerCase().startsWith('exp+'),
        ),
      }))
      .filter((entry) => entry.CFBundleURLSchemes.length > 0);
  }
  if (Array.isArray(infoPlist.NSBonjourServices)) {
    infoPlist.NSBonjourServices = infoPlist.NSBonjourServices.filter(
      (service) => service.toLocaleLowerCase().replace(/\.$/, '') !== '_expo._tcp',
    );
    if (infoPlist.NSBonjourServices.length === 0) delete infoPlist.NSBonjourServices;
  }
  if (
    typeof infoPlist.NSLocalNetworkUsageDescription === 'string'
    && infoPlist.NSLocalNetworkUsageDescription.includes('Expo Dev Launcher')
  ) {
    delete infoPlist.NSLocalNetworkUsageDescription;
  }
  for (const key of Object.keys(infoPlist)) {
    if (key.startsWith('EXDev') || key.startsWith('DEV_CLIENT_')) delete infoPlist[key];
  }
  return infoPlist;
}

function assertNoDevelopmentClientInfoPlist(infoPlist) {
  const serialized = JSON.stringify(infoPlist);
  if (/exp\+|_expo\._tcp|Expo Dev Launcher|"(?:EXDev|DEV_CLIENT_)/i.test(serialized)) {
    throw new Error(
      '[withFolioDistributionGuard] Expo development-client metadata leaked into Info.plist.',
    );
  }
}

function removeForbiddenStorePermissions(androidManifest) {
  for (const element of ANDROID_PERMISSION_ELEMENTS) {
    const permissions = androidManifest.manifest[element] ?? [];
    androidManifest.manifest[element] = permissions.filter(
      (permission) => !FORBIDDEN_STORE_PERMISSIONS.includes(permission.$?.['android:name']),
    );
  }
  androidManifest.manifest.$ ??= {};
  AndroidConfig.Manifest.ensureToolsAvailable(androidManifest);
  return AndroidConfig.Permissions.addBlockedPermissions(
    androidManifest,
    FORBIDDEN_STORE_PERMISSIONS,
  );
}

function assertNoForbiddenStorePermissions(androidManifest) {
  for (const element of ANDROID_PERMISSION_ELEMENTS) {
    const forbidden = (androidManifest.manifest[element] ?? []).find((permission) =>
      FORBIDDEN_STORE_PERMISSIONS.includes(permission.$?.['android:name'])
      && permission.$?.['tools:node'] !== 'remove',
    );
    if (forbidden) {
      throw new Error(
        `[withFolioDistributionGuard] ${element} leaked ${forbidden.$['android:name']}.`,
      );
    }
  }

  const blockers = new Set(
    (androidManifest.manifest['uses-permission'] ?? [])
      .filter((permission) => permission.$?.['tools:node'] === 'remove')
      .map((permission) => permission.$?.['android:name']),
  );
  const missing = FORBIDDEN_STORE_PERMISSIONS.filter((permission) => !blockers.has(permission));
  if (missing.length > 0) {
    throw new Error(
      `[withFolioDistributionGuard] missing manifest merge blockers for ${missing.join(', ')}.`,
    );
  }
}

function withFolioDistributionGuard(config) {
  let next = withSettingsGradle(config, (settingsConfig) => {
    if (settingsConfig.modResults.language !== 'groovy') {
      throw new Error('[withFolioDistributionGuard] Android settings.gradle must use Groovy.');
    }
    settingsConfig.modResults.contents = applyStoreAutolinkingGradleGuard(
      settingsConfig.modResults.contents,
    );
    assertStoreAutolinkingGradleGuard(settingsConfig.modResults.contents);
    return settingsConfig;
  });

  next = withPodfile(next, (podfileConfig) => {
    podfileConfig.modResults.contents = applyStorePodfileAutolinkingGuard(
      podfileConfig.modResults.contents,
    );
    assertStorePodfileAutolinkingGuard(podfileConfig.modResults.contents);
    return podfileConfig;
  });

  next = withInfoPlist(next, (infoPlistConfig) => {
    infoPlistConfig.modResults = removeDevelopmentClientInfoPlist(infoPlistConfig.modResults);
    assertNoDevelopmentClientInfoPlist(infoPlistConfig.modResults);
    return infoPlistConfig;
  });

  next = withAndroidManifest(next, (manifestConfig) => {
    manifestConfig.modResults = removeForbiddenStorePermissions(manifestConfig.modResults);
    manifestConfig.modResults = removeDevelopmentClientAndroidSchemes(manifestConfig.modResults);
    assertNoForbiddenStorePermissions(manifestConfig.modResults);
    assertNoDevelopmentClientAndroidScheme(manifestConfig.modResults);
    const mainApplication = AndroidConfig.Manifest.getMainApplicationOrThrow(
      manifestConfig.modResults,
    );
    const serialized = JSON.stringify(mainApplication);
    if (/FolioUpdater|expo\.modules\.dev(?:launcher|menu)/i.test(serialized)) {
      throw new Error(
        '[withFolioDistributionGuard] a store-excluded native module leaked into AndroidManifest.xml.',
      );
    }
    return manifestConfig;
  });
  return next;
}

module.exports = withFolioDistributionGuard;
module.exports.INSTALL_PACKAGES_PERMISSION = INSTALL_PACKAGES_PERMISSION;
module.exports.FORBIDDEN_STORE_PERMISSIONS = FORBIDDEN_STORE_PERMISSIONS;
module.exports.ANDROID_PERMISSION_ELEMENTS = ANDROID_PERMISSION_ELEMENTS;
module.exports.UPDATER_PACKAGE = UPDATER_PACKAGE;
module.exports.DEVELOPMENT_CLIENT_PACKAGES = DEVELOPMENT_CLIENT_PACKAGES;
module.exports.STORE_AUTOLINKING_EXCLUSIONS = STORE_AUTOLINKING_EXCLUSIONS;
module.exports.STORE_AUTOLINKING_MARKER = STORE_AUTOLINKING_MARKER;
module.exports.STORE_PODFILE_MARKER = STORE_PODFILE_MARKER;
module.exports.applyStoreAutolinkingGradleGuard = applyStoreAutolinkingGradleGuard;
module.exports.assertStoreAutolinkingGradleGuard = assertStoreAutolinkingGradleGuard;
module.exports.applyStorePodfileAutolinkingGuard = applyStorePodfileAutolinkingGuard;
module.exports.assertStorePodfileAutolinkingGuard = assertStorePodfileAutolinkingGuard;
module.exports.removeDevelopmentClientAndroidSchemes = removeDevelopmentClientAndroidSchemes;
module.exports.assertNoDevelopmentClientAndroidScheme = assertNoDevelopmentClientAndroidScheme;
module.exports.removeDevelopmentClientInfoPlist = removeDevelopmentClientInfoPlist;
module.exports.assertNoDevelopmentClientInfoPlist = assertNoDevelopmentClientInfoPlist;
module.exports.assertNoForbiddenStorePermissions = assertNoForbiddenStorePermissions;
module.exports.removeForbiddenStorePermissions = removeForbiddenStorePermissions;
module.exports.removeInstallPackagesPermission = removeForbiddenStorePermissions;
